version: v1.3.0

serve:
  public:
    base_url: http://localhost:4433/
    cors:
      enabled: true
      allowed_origins:
        - http://localhost:3000
      allowed_methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed_headers:
        - Content-Type
        - Authorization
        - Cookie
      exposed_headers:
        - Set-Cookie
      allow_credentials: true
  admin:
    base_url: http://kratos:4434/

session:
  whoami:
    required_aal: aal1

selfservice:
  default_browser_return_url: http://localhost:3000/
  allowed_return_urls:
    - http://localhost:3000
  methods:
    password:
      enabled: false
    webauthn:
      enabled: false
    passkey:
      enabled: true
      config:
        rp:
          display_name: Your Application name
          id: localhost
          origins:
            - http://localhost:3000
    code:
      enabled: true
      passwordless_enabled: true
      passwordless_login_fallback_enabled: false
      mfa_enabled: false

  flows:
    error:
      ui_url: http://localhost:3000/error

    settings:
      ui_url: http://localhost:3000/settings
      privileged_session_max_age: 15m
      required_aal: aal1

    recovery:
      enabled: false
      ui_url: http://localhost:3000/recovery
      use: code

    verification:
      enabled: false
      ui_url: http://localhost:3000/verification
      use: code
      after:
        default_browser_return_url: http://localhost:3000/

    logout:
      after:
        default_browser_return_url: http://localhost:3000/login

    login:
      ui_url: http://localhost:3000/login
      lifespan: 10m

    registration:
      enable_legacy_one_step: false
      lifespan: 10m
      ui_url: http://localhost:3000/register
      after:
        passkey:
          hooks:
            - hook: web_hook
              config:
                method: POST
                url: http://webhook-proxy/api/webhooks/post-registration
                body: base64://ZnVuY3Rpb24gKGN0eCkgewogIGV2ZW50OiAicmVnaXN0cmF0aW9uLmFmdGVyIiwKICBmbG93X2lkOiBjdHguZmxvdy5pZCwKICBmbG93X3R5cGU6IGN0eC5mbG93LnR5cGUsCiAgaWRlbnRpdHk6IHsKICAgIHNjaGVtYV9pZDogY3R4LmlkZW50aXR5LnNjaGVtYV9pZCwKICAgIHRyYWl0czogY3R4LmlkZW50aXR5LnRyYWl0cywKICB9LAogIHJlcXVlc3Q6IHsKICAgIHVybDogY3R4LnJlcXVlc3RfdXJsLAogICAgbWV0aG9kOiBjdHgucmVxdWVzdF9tZXRob2QsCiAgfSwKfQ==
                response:
                  ignore: false
                  parse: true
                headers:
                  Content-Type: application/json
            - hook: session
        code:
          hooks:
            - hook: web_hook
              config:
                method: POST
                url: http://webhook-proxy/api/webhooks/post-registration
                body: base64://ZnVuY3Rpb24gKGN0eCkgewogIGV2ZW50OiAicmVnaXN0cmF0aW9uLmFmdGVyIiwKICBmbG93X2lkOiBjdHguZmxvdy5pZCwKICBmbG93X3R5cGU6IGN0eC5mbG93LnR5cGUsCiAgaWRlbnRpdHk6IHsKICAgIHNjaGVtYV9pZDogY3R4LmlkZW50aXR5LnNjaGVtYV9pZCwKICAgIHRyYWl0czogY3R4LmlkZW50aXR5LnRyYWl0cywKICB9LAogIHJlcXVlc3Q6IHsKICAgIHVybDogY3R4LnJlcXVlc3RfdXJsLAogICAgbWV0aG9kOiBjdHgucmVxdWVzdF9tZXRob2QsCiAgfSwKfQ==
                response:
                  ignore: false
                  parse: true
                headers:
                  Content-Type: application/json
            - hook: session

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
